freeze: true
project:
  type: book
  output-dir: docs/
book:
  title: "OpenCRAVAT Vignettes"
  author: "Ted Laderas & Jasmine Baker"
  chapters:
    - index.qmd
    - "getting_started_web.qmd"
    - "getting_started_cli.qmd"
    - "making_annotator_modules.qmd"
    - "filtering.qmd"
    - "making_a_package.qmd"
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false

format:
  html:
    theme: cosmo
    fig-align: center
  #pdf:
  #  documentclass: scrreprt
